### ISSUE TITLE
0.20.0 was never published

### ISSUE THREAD

**Issue by Fishrock123** [georust/geojson#146]
https://crates.io/crates/geojson/versions is missing 0.20.0, despite there being an apparent release commit: https://github.com/georust/geojson/commit/80a08e6a80f2479c459e5b77a5dd22ebeab2f46c, but no tag.

**Comment by urschrei** [comment]
Ah, that's because a load of nice additional conversions landed sort of out-of-the-blue, and we didn't want to exclude them. I'm hopefully going to revisit the docs this weekend to see whether they can benefit from the new features, and then push out a new release early next week. For the sake of clarity: a release commit is never a release commit until it's been tagged, because we are slightly less organised than we would like to be. Sorry if this held you up!

**Comment by urschrei** [comment]
Published!
